export { default as Navbar } from './Navbar'
export { default as Layout } from './Layout'
export { default as Hero } from './Hero'
export { default as HowToPlay } from './HowToPlay'
export { default as AboutUs } from './AboutUs'