export { default as Navbar } from './Navbar'
export { default as Layout } from './Layout'
export { default as Hero } from './Hero'
export { default as HowToPlay } from './HowToPlay'
export { default as AboutUs } from './AboutUs'
export { default as MovieMania } from './MovieMania'
export { default as Newsletter } from './Newsletter'
export { default as Footer } from './Footer'